[[resources-accounts]]
== Account-Service
Handles the accounts of the tenants of the HSKA ERP system.
The `accounts` resource is used to create, list, update and delete accounts.

=== GET
==== List all accounts of tenants
|===
|Path|Type|Description

|`[].id`
|`Number`
|The account ID

|`[].email`
|`String`
|the email address of the account

|`[].username`
|`String`
|the username of the account

|`[].password`
|`String`
|the password of the user

|`[].tenantStatus`
|`String`
|the status of the tenant PROSPECT or CUSTOMER, which is empty in ADMIN accounts

|`[].tenantId`
|`Varies`
|the corresponding tenantId, which is only set in USER accounts

|`[].accountType`
|`String`
|the type of the account: ADMIN, TENANT or USER

|`[].firstname`
|`String`
|the firstname of the account owner

|`[].lastname`
|`String`
|the lastname of the account owner

|`[].company`
|`String`
|the company of the account owner

|`[].services.[]`
|`Object`
|the services/modules this account can use

|===

===== Example request
[source,bash]
----
$ curl 'http://localhost:8080/accounts' -i -H 'Accept: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42'
----

[source,http,options="nowrap"]
----
GET /accounts HTTP/1.1
Accept: application/json
Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42
Host: localhost:8080

----

===== Example response
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: 1073

[ {
  "id" : 1,
  "email" : "prospect1@test.org",
  "username" : "",
  "password" : "LTg0MDQ2MjgxOQ==",
  "firstname" : "",
  "lastname" : "",
  "company" : "tenant1Company",
  "tenantId" : null,
  "tenantStatus" : "PROSPECT",
  "accountType" : "TENANT",
  "services" : [ {
    "name" : "PRODUCT"
  }, {
    "name" : "CUSTOMER"
  }, {
    "name" : "VENDOR"
  } ]
}, {
  "id" : 2,
  "email" : "prospect2@test.org",
  "username" : "",
  "password" : "LTQ0MDA0MzMyNg==",
  "firstname" : "",
  "lastname" : "",
  "company" : "",
  "tenantId" : null,
  "tenantStatus" : "PROSPECT",
  "accountType" : "TENANT",
  "services" : [ {
    "name" : "PRODUCT"
  }, {
    "name" : "CUSTOMER"
  }, {
    "name" : "VENDOR"
  } ]
}, {
  "id" : 3,
  "email" : "user@test.org",
  "username" : "",
  "password" : "ODk2MzM2MDgz",
  "firstname" : "John",
  "lastname" : "Doe",
  "company" : "tenant1Company",
  "tenantId" : 1,
  "tenantStatus" : "PROSPECT",
  "accountType" : "USER",
  "services" : [ {
    "name" : "PRODUCT"
  }, {
    "name" : "CUSTOMER"
  }, {
    "name" : "VENDOR"
  } ]
} ]
----


==== Get account by its unique id
|===
|Path|Type|Description

|`id`
|`Number`
|The account ID

|`email`
|`String`
|the email address of the account

|`username`
|`String`
|the username of the account

|`password`
|`String`
|the password of the user

|`tenantStatus`
|`String`
|the status of the tenant PROSPECT or CUSTOMER, which is empty in ADMIN accounts

|`tenantId`
|`Null`
|the corresponding tenantId, which is only set in USER accounts

|`accountType`
|`String`
|the type of the account: ADMIN, TENANT or USER

|`firstname`
|`String`
|the firstname of the account owner

|`lastname`
|`String`
|the lastname of the account owner

|`company`
|`String`
|the company of the account owner

|`services.[]`
|`Array`
|the services/modules this account can use

|===

===== Example request
[source,bash]
----
$ curl 'http://localhost:8080/accounts/1' -i -H 'Accept: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42'
----

[source,http,options="nowrap"]
----
GET /accounts/1 HTTP/1.1
Accept: application/json
Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42
Host: localhost:8080

----

===== Example response
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: 348

{
  "id" : 1,
  "email" : "prospect1@test.org",
  "username" : "",
  "password" : "LTExMTMxNzQ0MjE=",
  "firstname" : "",
  "lastname" : "",
  "company" : "",
  "tenantId" : null,
  "tenantStatus" : "PROSPECT",
  "accountType" : "TENANT",
  "services" : [ {
    "name" : "PRODUCT"
  }, {
    "name" : "CUSTOMER"
  }, {
    "name" : "VENDOR"
  } ]
}
----

And if the account does not exist:
[source,http,options="nowrap"]
----
HTTP/1.1 404 Not Found

----


=== POST
==== Create tenant account
Only the e-Mail address is required for creating a prospect account. The generated password is returned.

|===
|Path|Type|Description

|`email`
|`String`
|The email-address of the tenant

|===

===== Example request
[source,bash]
----
$ curl 'http://localhost:8080/accounts' -i -X POST -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42' -H 'Content-Type: application/json' -d '{"email":"test@mail.org"}'
----

[source,http,options="nowrap"]
----
POST /accounts HTTP/1.1
Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42
Content-Type: application/json
Host: localhost:8080
Content-Length: 25

{"email":"test@mail.org"}
----

===== Example response
[source,http,options="nowrap"]
----
HTTP/1.1 201 Created
Content-Type: text/plain;charset=UTF-8
Content-Length: 16

LTExNTc5NjMwMg==
----


==== Create user account
The first-, lastname and e-Mail address is required for creating a user account. The generated password is returned.

|===
|Path|Type|Description

|`firstname`
|`String`
|The first name of the user

|`lastname`
|`String`
|The last name of the user

|`email`
|`String`
|The email-address of the user

|===

===== Example request
[source,bash]
----
$ curl 'http://localhost:8080/accounts/1' -i -X POST -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42' -H 'Content-Type: application/json' -d '{"firstname":"John","email":"newuser@mail.org","lastname":"Doe"}'
----

[source,http,options="nowrap"]
----
POST /accounts/1 HTTP/1.1
Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42
Content-Type: application/json
Host: localhost:8080
Content-Length: 64

{"firstname":"John","email":"newuser@mail.org","lastname":"Doe"}
----

===== Example response
[source,http,options="nowrap"]
----
HTTP/1.1 201 Created
Content-Type: text/plain;charset=UTF-8
Content-Length: 16

LTE3MDc2NDM2NjU=
----

=== PATCH
==== Update account
For Upgrading the `status` use `/upgrade` and for adding new services use the `/addservice` resource.

===== Example request for Tenant
|===
|Path|Type|Description

|`id`
|`String`
|The id of the user

|`username`
|`String`
|The name of the user

|`firstname`
|`String`
|The first name of the user

|`lastname`
|`String`
|The last name of the user

|`email`
|`String`
|The email-address of the user

|`company`
|`String`
|The company name of the user

|===

[source,bash]
----
$ curl 'http://localhost:8080/accounts' -i -X PATCH -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42' -H 'Content-Type: application/json' -d '{"firstname":"John","company":"VR Stuff","id":"1","email":"test123@mail.org","username":"newUsername","lastname":"Doe"}'
----

[source,http,options="nowrap"]
----
PATCH /accounts HTTP/1.1
Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42
Content-Type: application/json
Host: localhost:8080
Content-Length: 119

{"firstname":"John","company":"VR Stuff","id":"1","email":"test123@mail.org","username":"newUsername","lastname":"Doe"}
----

===== Example response for Tenant
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: 372

{
  "id" : 1,
  "email" : "test123@mail.org",
  "username" : "newUsername",
  "password" : "MTAwNDk2OTY1Ng==",
  "firstname" : "John",
  "lastname" : "Doe",
  "company" : "VR Stuff",
  "tenantId" : null,
  "tenantStatus" : "PROSPECT",
  "accountType" : "TENANT",
  "services" : [ {
    "name" : "PRODUCT"
  }, {
    "name" : "CUSTOMER"
  }, {
    "name" : "VENDOR"
  } ]
}
----

==== Upgrade prospect to customer
This can only be done for `TENANT` accounts

===== Example request
[source,bash]
----
$ curl 'http://localhost:8080/accounts/1/upgrade' -i -X PATCH -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42' -H 'Content-Type: application/json'
----

[source,http,options="nowrap"]
----
PATCH /accounts/1/upgrade HTTP/1.1
Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42
Content-Type: application/json
Host: localhost:8080

----

===== Example response
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: 344

{
  "id" : 1,
  "email" : "testuser2@mail.org",
  "username" : "",
  "password" : "MTg0MzE0MzE1",
  "firstname" : "",
  "lastname" : "",
  "company" : "",
  "tenantId" : null,
  "tenantStatus" : "CUSTOMER",
  "accountType" : "TENANT",
  "services" : [ {
    "name" : "PRODUCT"
  }, {
    "name" : "CUSTOMER"
  }, {
    "name" : "VENDOR"
  } ]
}
----


==== Add service(s)
This can only be done in `CUSTOMER` state for `TENANTS`

===== Example request
|===
|Path|Type|Description

|`[].name`
|`String`
|The name of the service to add

|===

[source,bash]
----
$ curl 'http://localhost:8080/accounts/1/addservice' -i -X PATCH -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42' -H 'Content-Type: application/json' -d '[{"name":"CUSTOMER"}]'
----

[source,http,options="nowrap"]
----
PATCH /accounts/1/addservice HTTP/1.1
Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42
Content-Type: application/json
Host: localhost:8080
Content-Length: 21

[{"name":"CUSTOMER"}]
----

===== Example response
|===
|Path|Type|Description

|`id`
|`Number`
|The account ID

|`email`
|`String`
|the email address of the account

|`username`
|`String`
|the username of the account

|`password`
|`String`
|the password of the user

|`tenantStatus`
|`String`
|the status of the tenant PROSPECT or CUSTOMER, which is empty in ADMIN accounts

|`tenantId`
|`Null`
|the corresponding tenantId, which is only set in USER accounts

|`accountType`
|`String`
|the type of the account: ADMIN, TENANT or USER

|`firstname`
|`String`
|the firstname of the account owner

|`lastname`
|`String`
|the lastname of the account owner

|`company`
|`String`
|the company of the account owner

|`services.[]`
|`Array`
|the services/modules this account can use

|===

[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: 375

{
  "id" : 1,
  "email" : "testuser2@mail.org",
  "username" : "",
  "password" : "NzU2OTE1OTU3",
  "firstname" : "",
  "lastname" : "",
  "company" : "",
  "tenantId" : null,
  "tenantStatus" : "PROSPECT",
  "accountType" : "TENANT",
  "services" : [ {
    "name" : "PRODUCT"
  }, {
    "name" : "CUSTOMER"
  }, {
    "name" : "CUSTOMER"
  }, {
    "name" : "VENDOR"
  } ]
}
----


==== Remove service(s)
This can only be done in `CUSTOMER` state for `TENANTS`

===== Example request
|===
|Path|Type|Description

|`[].name`
|`String`
|The name of the service to remove

|===

[source,bash]
----
$ curl 'http://localhost:8080/accounts/1/rmservice' -i -X PATCH -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42' -H 'Content-Type: application/json' -d '[{"name":"CUSTOMER"}]'
----

[source,http,options="nowrap"]
----
PATCH /accounts/1/rmservice HTTP/1.1
Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42
Content-Type: application/json
Host: localhost:8080
Content-Length: 21

[{"name":"CUSTOMER"}]
----

===== Example response
|===
|Path|Type|Description

|`id`
|`Number`
|The account ID

|`email`
|`String`
|the email address of the account

|`username`
|`String`
|the username of the account

|`password`
|`String`
|the password of the user

|`tenantStatus`
|`String`
|the status of the tenant PROSPECT or CUSTOMER, which is empty in ADMIN accounts

|`tenantId`
|`Null`
|the corresponding tenantId, which is only set in USER accounts

|`accountType`
|`String`
|the type of the account: ADMIN, TENANT or USER

|`firstname`
|`String`
|the firstname of the account owner

|`lastname`
|`String`
|the lastname of the account owner

|`company`
|`String`
|the company of the account owner

|`services.[]`
|`Array`
|the services/modules this account can use

|===

[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: 313

{
  "id" : 1,
  "email" : "testuser2@mail.org",
  "username" : "",
  "password" : "LTY1MDU1MzE=",
  "firstname" : "",
  "lastname" : "",
  "company" : "",
  "tenantId" : null,
  "tenantStatus" : "PROSPECT",
  "accountType" : "TENANT",
  "services" : [ {
    "name" : "PRODUCT"
  }, {
    "name" : "VENDOR"
  } ]
}
----


=== DELETE
==== Delete client account
You can only delete you own account.

===== Example request
[source,bash]
----
$ curl 'http://localhost:8080/accounts/1' -i -X DELETE -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42' -H 'Content-Type: application/json'
----

[source,http,options="nowrap"]
----
DELETE /accounts/1 HTTP/1.1
Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42
Content-Type: application/json
Host: localhost:8080

----

===== Example response
[source,http,options="nowrap"]
----
HTTP/1.1 204 No Content

----

And if the account does not exist:
[source,http,options="nowrap"]
----
HTTP/1.1 404 Not Found

----
