[account]
== Account-Service

Handles the accounts of the tenants of the HSKA ERP system.
The tenant is identified by the 'Bearer Header Token'.

=== GET

==== List all accounts of tenants

===== Example Request
[source,bash,options="nowrap"]
----
$ curl 'http://DOCKER-HOST:8080/accounts' -i -H 'Accept: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42'
----

===== Example Response
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length:

[
 {
  "id":"1",
  "username": "",
  "firstname":"",
  "lastname":"",
  "email":"",
  "company":"",
  "tenantId": "",
  "type": "TENANT"
  "status":"PROSPECT",
  "services": [
    "name":"PRODUCT",
    "name":"CUSTOMER",
    "name":"SALES",
  ]
 },
 {
  "id":"2"
  "username": "",
  "firstname":"",
  "lastname":"",
  "email":"",
  "company":"",
  "tenantId:"1",
  "type": "USER"
 },
 {
   "id":"3"
   "username": "",
   "firstname":"",
   "lastname":"",
   "email":"",
   "company":"null",
   "tenantId:"null",
   "type": "ADMIN"
  }
]

----

==== Get account by its unique id

===== Example Request
[source,bash,options="nowrap"]
----
$ curl 'http://DOCKER-HOST:8080/accounts/{id}' -i -H 'Accept: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42'
----
===== Example Response
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length:

{
 "id":"1",
 "username": "",
 "firstname":"",
 "lastname":"",
 "email":"",
 "company":"",
 "tenantId": "null",
 "type": "TENANT"
 "status":"PROSPECT",
 "services": [
   "name":"PRODUCT",
   "name":"CUSTOMER",
   "name":"SALES",
 ]
}

----

=== POST

==== Create a new account for a client
Only the e-Mail address is required for creating a prospect account. The generated password is returned.

===== Example Request
[source,bash,options="nowrap"]
----
$ curl 'http://DOCKER-HOST:8080/accounts' -i -X POST -H 'Content-Type: application/json' -d '{"email":""}'
----

===== Example Response
[source,http,options="nowrap"]
----
HTTP/1.1 201 Created
Content-Type: text/plain;charset=UTF-8
Content-Length:

84eeeb5fb09da9e2ed197cb3c1f1f0575f3bef33
----

==== Create a new account for a user/employee of a client
The first-, lastname and e-Mail address is required for creating a user account. The generated password is returned.

===== Example Request
[source,bash,options="nowrap"]
----
$ curl 'http://DOCKER-HOST:8080/accounts/{tenantId}' -i -X POST -H 'Content-Type: application/json' -d '{"firstname:": "", "lastname": "", email":""}'
----

===== Example Response
[source,http,options="nowrap"]
----
HTTP/1.1 201 Created
Content-Type: text/plain;charset=UTF-8
Content-Length:

84eeeb5fb09da9e2ed197cb3c1f1f0575f3we22
----

=== PUT

==== Update an existing account for a client
Anything but the `username` can be updated. For Upgrading the `status` use `/upgrade` and for
adding new services use the `addservice` resource.

===== Example Request for Tenant
A tenant can only update personal data fields. He cannot change his status. This can only
be done by an `Admin`.
[source,bash,options="nowrap"]
----
$ curl 'http://DOCKER-HOST:8080/accounts' -i -X PUT -H 'Content-Type: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42' -d '{"username":"", "firstname":"", "lastname":"", "company":"", "email":""}'
----

===== Example Response
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length:

{
 "id":"1",
 "username": "",
 "firstname":"",
 "lastname":"",
 "email":"",
 "company":""
}
----

===== Example Request for Admin
A admin can edit all data fields.
[source,bash,options="nowrap"]
----
$ curl 'http://DOCKER-HOST:8080/accounts' -i -X PUT -H 'Content-Type: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42' -d '{"username":"", "firstname":"", "lastname":"", "company":"", "email":"", "status":"PROSPECT", "services": ["name":"PRODUCT","name":"CUSTOMER","name":"SALES"]}'
----

===== Example Response
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length:

{
 "id":"1",
 "username": "",
 "firstname":"",
 "lastname":"",
 "email":"",
 "company":"",
 "tenantId": "null",
 "type": "TENANT"
 "status":"PROSPECT",
 "services": [
   "name":"PRODUCT",
   "name":"CUSTOMER",
   "name":"SALES",
 ]
}
----

==== Upgrade tenant from prospect to customer

===== Example Request
[source,bash,options="nowrap"]
----
$ curl 'http://DOCKER-HOST:8080/accounts/upgrade/{id}' -i -X PUT -H 'Content-Type: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42'
----

===== Example Response
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: 0

{
 "id":"",
 "username": "",
 "firstname":"",
 "lastname":"",
 "email":"",
 "company":"",
 "tenantId": "null",
 "type": "TENANT"
 "status":"CUSTOMER",
 "services": [
   "name":"PRODUCT",
   "name":"CUSTOMER",
   "name":"SALES",
 ]
}
----

==== Add new services for a customer

===== Example Request
[source,bash,options="nowrap"]
----
$ curl 'http://DOCKER-HOST:8080/accounts/addservice/{id}' -i -X PUT -H 'Content-Type: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42' -d '[ "name":"VENDOR" ]'
----

===== Example Response
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: 0

{
 "id":"1",
 "username": "",
 "firstname":"",
 "lastname":"",
 "email":"",
 "company":"",
 "tenantId": "null",
 "type": "TENANT"
 "status":"PROSPECT",
 "services": [
   "name":"PRODUCT",
   "name":"CUSTOMER",
   "name":"SALES",
   "name":"VENDORS",
 ]
}
----

==== Remove services for a tenant in CUSTOMER state

===== Example Request
[source,bash,options="nowrap"]
----
$ curl 'http://DOCKER-HOST:8080/accounts/removeservice/{id}' -i -X PUT -H 'Content-Type: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42' -d '[ "SALES", "VENDOR" ]'
----

===== Example Response
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: 0

{
 "id":"1",
 "username": "",
 "firstname":"",
 "lastname":"",
 "email":"",
 "company":"",
 "tenantId": "null",
 "type": "TENANT"
 "status":"CUSTOMER",
 "services": [
   "name":"PRODUCT",
   "name":"CUSTOMER",
 ]
}
----

=== DELETE

==== Delete client account
You can only delete you own account.

===== Example Request
[source,bash,options="nowrap"]
----
$ curl 'http://DOCKER-HOST:8080/accounts/{id}' -i -X DELETE -H 'Accept: application/json' -H 'Authorization: Bearer: 0b79bab50daca910b000d4f1a2b675d604257e42'
----
===== Example Response
[source,http,options="nowrap"]
----
HTTP/1.1 204 No Content

----
